### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by welcometothemachine** [tableau-mkt/dcm-dfa-wdc#11]
Does the web connector still work? I am trying to log in and I am getting an "Internal Server Error" message. I know it's not a permission error as I have access to several reports in doubleclick. Any idea of what might be going on? Thank you!!

**Comment by njsa04** [comment]
Same as above - does this still work?

**Comment by njsa04** [comment]
Hi @iamEAP - can you confirm if this still works?
I get  "Internal Server Error" when connecting.
I think the system needs a profileid but I don't see a way to enter that here.
Let me know - thanks!

**Comment by njsa04** [comment]
@welcometothemachine did you make any progress?

**Comment by welcometothemachine** [comment]
@njsa04 None, it still gives me the same error

**Comment by iamEAP** [comment]
Hey @welcometothemachine and @njsa04, my hunch is that this error message is a direct result of #10.  The fix could be as simple as updating the dependency on `googleapis` here: https://github.com/tableau-mkt/dcm-dfa-wdc/blob/master/package.json#L26

If one of you could open up a pull request with that update, I'd be happy to help validate.

**Comment by njsa04** [comment]
I’m a novice when it comes to github.  I’ll try to google for how to do it.

**Comment by njsa04** [comment]
@iamEAP I just made changes and opened a pull request.  would love to see if it works...

**Comment by iamEAP** [comment]
Thanks very much for your contribution @njsa04!  I finally found some time to review and merge.

For those who find this thread: this issue should be resolved in `v1.2.0`, which I just deployed to https://dcm-dfa-wdc.herokuapp.com/.  If you encounter any additional issues, please open new issues!  Thanks.
