### ISSUE TITLE
First, Sign in to Google not working. 

### ISSUE THREAD

**Issue by jaiswalpuja** [tableau-mkt/dcm-dfa-wdc#14]
Using the latest version for DFA 2.6. 

Any help will be greatly appreciated. 

Thanks!
Puja

**Comment by denisq** [comment]
Same here, first login (passed the Google OAuth) but get the following error:
There was a problem retrieving data: "error" with error thrown: "Internal Server Error"

**Comment by iamEAP** [comment]
Hello all, this issue should be resolved in `v1.2.0`, which I just deployed to https://dcm-dfa-wdc.herokuapp.com/.  If you encounter any additional issues, please open new issues!  Thanks.

**Comment by denisq** [comment]
The site throws an error:  Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.
