### ISSUE TITLE
Application error on the hosted version

### ISSUE THREAD

**Issue by denisq** [tableau-mkt/dcm-dfa-wdc#15]
When I go to the hosted version (https://dcm-dfa-wdc.herokuapp.com/), I get an application error:

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details

**Comment by iamEAP** [comment]
Thanks for the report @denisq.  Looks to have been due to the hosted version running an outdated version of node.js.  Example / hosted version is up-to-date now.

**Comment by denisq** [comment]
@iamEAP, it seems that as soon as I use the connector, your webpage breaks. How can that be?
