### ISSUE TITLE
I only see the most recent report

### ISSUE THREAD

**Issue by MullenEuroStarHero** [tableau-mkt/dcm-dfa-wdc#6]
Is there a reason I only see the most recent report in the drop down.  is that a code issue or a setting somewhere?

**Comment by iamEAP** [comment]
Hmm...  Are you sure it's the most recent report?  If I recall correctly, there's a limit in the way the API is designed where you'll only be able to pull down reports that you own or have created yourself (not necessarily everything you have access to through the web UI).

**Comment by MullenEuroStarHero** [comment]
It’s not even report I have created.  Yes most recent.

[MullenLowe U.S.]<http://mullenloweus.com/ws>



Aline Kasliner

Manager Of Consumer Insights

525 Vine St., Suite 340, Winston-Salem, NC 27101

  M. (904)891-9079

mullenloweus.com/ws<http://mullenloweus.com/ws>

[Facebook]<https://www.facebook.com/MullenLoweUS>

[Twitter]<https://www.twitter.com/MullenLoweUS>

[Instagram]<http://www.instagram.com/MullenLoweUS>

[Youtube]<https://www.youtube.com/c/MullenLoweUS>

[Linkedin]<https://www.linkedin.com/company/MullenLowe-US>

**Comment by iamEAP** [comment]
Cleaning out the backlog...  Going to close this for now.  Feel free to open if you have additional details!
