### ISSUE TITLE
Hosted version - Login button not working

### ISSUE THREAD

**Issue by yagihashib** [tableau-mkt/dcm-dfa-wdc#7]
Hi there,

I noticed that the hosted version of this won't respond after clicking the 'Sign-in to Google button':
https://dcm-dfa-wdc.herokuapp.com/

I'm trying this on Google Chrome. Is this webapp still being supported?

Thanks!

**Comment by iamEAP** [comment]
Hey @yagihashib,

That link won't be useful to you in Google Chrome, you'll want to copy/paste the URL into the Web Data Connector dialog in [Tableau Desktop](https://www.tableau.com/products/desktop).

![](https://i.ytimg.com/vi/hjFvEv5M6cs/maxresdefault.jpg)

**Comment by yagihashib** [comment]
gotcha. Thank you!
